const String BaseUrl = "https://iijcwjoiodsgprwjztas.supabase.co";
const String AnonKey ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpamN3am9pb2RzZ3Byd2p6dGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjM0MjMzOTksImV4cCI6MjAzODk5OTM5OX0.iSr1P_qOOsrpYtSswlD4Je83GZRpAzeaa7TqDB3mzWc';
