// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBh7ripfS9Y5XLUVrgkd5H0XdvvvpPvSo',
    appId: '1:181961421151:web:a1f1bbf70cfadc49dfc6ea',
    messagingSenderId: '181961421151',
    projectId: 'gymday-ee08c',
    authDomain: 'gymday-ee08c.firebaseapp.com',
    databaseURL: 'https://gymday-ee08c.firebaseio.com',
    storageBucket: 'gymday-ee08c.appspot.com',
    measurementId: 'G-NQZVD6LYCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHOUGH4jgpfU8B6KFTaK_Uip1TwGmXuY',
    appId: '1:181961421151:android:37cc300d28f9d6afdfc6ea',
    messagingSenderId: '181961421151',
    projectId: 'gymday-ee08c',
    databaseURL: 'https://gymday-ee08c.firebaseio.com',
    storageBucket: 'gymday-ee08c.appspot.com',
     );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArxy7nXdMZmhRxqoL69KIvs6yVViTvlR4',
    appId: '1:181961421151:ios:d9c3bf1932c11bebdfc6ea',
    messagingSenderId: '181961421151',
    projectId: 'gymday-ee08c',
    databaseURL: 'https://gymday-ee08c.firebaseio.com',
    storageBucket: 'gymday-ee08c.appspot.com',
    androidClientId: '181961421151-2dirj5r60vmcb3ijvdb9b4ogkhtpeo4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrCareerPlatform',
  );
}
