// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC65iFDkem4voUWid8lR1ahiOM0oOACn8Q',
    appId: '1:266149675336:web:ad30a2671dbb6d7388b37d',
    messagingSenderId: '266149675336',
    projectId: 'hrapp-e4639',
    authDomain: 'hrapp-e4639.firebaseapp.com',
    storageBucket: 'hrapp-e4639.firebasestorage.app',
    measurementId: 'G-N3F294SQCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHSftQzpRlIKzM-4JiTzNdjSpoMJn1hw',
    appId: '1:266149675336:android:9674bc3dba96d68288b37d',
    messagingSenderId: '266149675336',
    projectId: 'hrapp-e4639',
    storageBucket: 'hrapp-e4639.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJgxTfTIoLQU9NfzyuNEcJFvNwayRj9mI',
    appId: '1:266149675336:ios:84dc0425d89e3e3988b37d',
    messagingSenderId: '266149675336',
    projectId: 'hrapp-e4639',
    storageBucket: 'hrapp-e4639.firebasestorage.app',
    iosBundleId: 'com.example.hrCareerPlatform',
  );

}